name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libcurl4-openssl-dev libpqxx-dev pkg-config postgresql

    - name: Start PostgreSQL service
      run: |
        sudo systemctl start postgresql

    - name: Create test database
      run: |
        sudo su - postgres <<EOF
          psql -c "CREATE DATABASE mydb;"
          psql -c "CREATE USER postgres WITH PASSWORD '20ufodop1';"
          psql -c "GRANT ALL PRIVILEGES ON DATABASE mydb TO postgres;"
        EOF

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run executable
      run: |
        cd build
        ./ExchangeRateCbr
        
    #services:
    #  postgres:
    #    image: postgres:17
    #    env:
    #      POSTGRES_USER: postgres
    #      POSTGRES_PASSWORD: 20ufodop1
    #      POSTGRES_DB: mydb
    #    ports:
    #      - 5432:5432
    #    options: >-
    #      --health-cmd pg_isready
    #      --health-interval 10s
    #      --health-timeout 5s
    #      --health-retries 5
