name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++ and libcurl
      run: sudo apt-get install -y g++ libcurl4-openssl-dev
    
    - name: Install libpqxx
      run: sudo apt-get install -y libpqxx-dev
  
    - name: Set CMAKE_PREFIX_PATH
      run: echo "CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/pqxx" >> $GITHUB_ENV
  
    - name: Build 
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ./test_executable
