name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libcurl4-openssl-dev libpqxx-dev pkg-config postgresql

    - name: Start PostgreSQL service
      run: |
        sudo systemctl start postgresql

    - name: Create test database
      run: |
        sudo su - postgres <<EOF
          psql -c "CREATE DATABASE test_utf;"
          psql -c "CREATE USER postgres WITH PASSWORD '20ufodop1';"
          psql -c "GRANT ALL PRIVILEGES ON DATABASE test_utf TO postgres;"
        EOF

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run executable
      run: |
        cd build
        ./ExchangeRateCbr
