name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libcurl4-openssl-dev libpqxx-dev pkg-config postgresql

    - name: Configure PostgreSQL
      run: |
        # Allow connections from localhost
        echo "host all all 127.0.0.1/32 trust" | sudo tee -a /etc/postgresql/*/main/pg_hba.conf
        
        # Enable TCP/IP connections
        echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/*/main/postgresql.conf
        
        # Restart PostgreSQL to apply changes
        sudo systemctl restart postgresql

    - name: Create test database
      run: |
        sudo -u postgres psql -c "CREATE DATABASE mydb;"
        sudo -u postgres psql -c "CREATE USER service WITH PASSWORD '20ufodop1';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mydb TO service;"
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run executable
      run: |
        cd build
        ./ExchangeRateCbr
