name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libcurl4-openssl-dev libpqxx-dev pkg-config postgresql

    - name: Start PostgreSQL service
      run: |
        sudo systemctl start postgresql
        sleep 5 # Ждем немного, чтобы сервис успел запуститься

    - name: Create test database
      run: |
        sudo su - postgres -c "psql -c 'CREATE DATABASE mydb;' || echo 'Database already exists.'"
        sudo su - postgres -c "psql -c 'DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = ''postgres'') THEN CREATE USER postgres WITH PASSWORD ''20ufodop1''; END IF; END \$\$;'"
        sudo su - postgres -c "psql -c 'GRANT ALL PRIVILEGES ON DATABASE mydb TO postgres;'"

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run executable
      run: |
        cd build
        ./ExchangeRateCbr
