name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++ and  libcur
      run: sudo apt-get install g++ libcurl4-openssl-dev
    
    - name: Install libpqxx
      run: sudo apt-get install libpqxx-dev
  
    - name: Build 
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ./test_executable 
