name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libcurl4-openssl-dev libpqxx-dev pkg-config

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run executable
      run: |
        cd build
        ./ExchangeRateCbr
